Algoritmo "semnome"
//vetores

Var
vet1, vet2: vetor[1..5] de inteiro
i: inteiro

Inicio

para i de 1 ate 5 passo 1 faca
     escreval("Vet1: pos ", i, ": ")
     leia(vet1[i])

fimpara
escreval()

para i de 1 ate 5 passo 1 faca
     escreval("Vet1: pos ", i, ": ")
     leia(vet2[i])

fimpara
escreva()
escreval("Soma: ")

para i  de 1 ate 5 passo 1 faca
        escreva(vet1[i] + vet2[i])
fimpara
Fimalgoritmo