Algoritmo "semnome"
//vetores

Var
n1,n2,n3,n4,n5,n6,n7,n8,n9,n10: inteiro
soma, media: real

Inicio
soma<- 0
escreva("valor 1: ")
leia(n1)
escreva("Valor 2: ")
leia(n2)
escreva("Valor 3: ")
leia(n3)
escreva("Valor 4: ")
leia(n4)
escreva("Valor 5: ")
leia(n5)
escreva("Valor 6: ")
leia(n6)
escreva("Valor 7: ")
leia(n7)
escreva("Valor 8: ")
leia(n8)
escreva("Valor 9: ")
leia(n9)
escreva("Valor 10: ")
leia(n10)

soma<-n1+n2+n3+n4+n5+n6+n7+n8+n9+n10
media<- soma/10
escreval("média: ", media)

Fimalgoritmo